uploads = []
outputs = []

[[generated]]
id = "nzjarLEUgt-eVswVSBi3O"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Fmel_PrPzceKTH9jOM7Vt"
uri = "file://artifacts/mobile/assets/images/splash-icon.png"
type = "image"
title = "generated_image"
